// packages/solid/src/hooks/useHttp.ts
/**
 * useHttp - Solid HTTP 请求 Hook
 */

import { createSignal, createEffect, type Accessor } from 'solid-js'
import type { HttpClient, RequestConfig } from '@ldesign/http-core'

/**
 * useHttp 选项
 */
export interface UseHttpOptions<T = unknown> extends RequestConfig {
  /** 是否立即执行 */
  immediate?: boolean
  /** 错误回调 */
  onError?: (error: Error) => void
  /** 成功回调 */
  onSuccess?: (data: T) => void
}

/**
 * useHttp 返回值
 */
export interface UseHttpReturn<T = unknown> {
  /** 响应数据 */
  data: Accessor<T | null>
  /** 加载状态 */
  loading: Accessor<boolean>
  /** 错误信息 */
  error: Accessor<Error | null>
  /** 执行请求 */
  execute: (config?: RequestConfig) => Promise<void>
  /** 重置状态 */
  reset: () => void
}

/**
 * HTTP 请求 Hook (Solid)
 * 
 * @param url - 请求 URL
 * @param options - 请求选项
 * @param client - HTTP 客户端实例
 * @returns HTTP 请求状态和方法
 * 
 * @example
 * ```tsx
 * import { useHttp } from '@ldesign/http-solid'
 * 
 * function UserList() {
 *   const { data, loading, error } = useHttp(() => '/api/users')
 *   
 *   return (
 *     <div>
 *       {loading() && <div>Loading...</div>}
 *       {error() && <div>Error: {error().message}</div>}
 *       {data() && <div>{JSON.stringify(data())}</div>}
 *     </div>
 *   )
 * }
 * ```
 */
export function useHttp<T = unknown>(
  url: Accessor<string> | string,
  options: UseHttpOptions<T> = {},
  client?: HttpClient,
): UseHttpReturn<T> {
  const [data, setData] = createSignal<T | null>(null)
  const [loading, setLoading] = createSignal(false)
  const [error, setError] = createSignal<Error | null>(null)

  /**
   * 执行 HTTP 请求
   */
  async function execute(config: RequestConfig = {}): Promise<void> {
    if (!client) {
      setError(new Error('HTTP client not provided'))
      return
    }

    setLoading(true)
    setError(null)

    try {
      const requestUrl = typeof url === 'function' ? url() : url
      const response = await client.request<T>({
        url: requestUrl,
        method: 'GET',
        ...options,
        ...config,
      })

      setData(() => response.data)
      options.onSuccess?.(response.data)
    }
    catch (e) {
      const err = e as Error
      setError(err)
      options.onError?.(err)
    }
    finally {
      setLoading(false)
    }
  }

  /**
   * 重置状态
   */
  function reset(): void {
    setData(null)
    setLoading(false)
    setError(null)
  }

  // 立即执行
  createEffect(() => {
    if (options.immediate !== false) {
      execute()
    }
  })

  return {
    data,
    loading,
    error,
    execute,
    reset,
  }
}

// packages/react/src/useHttp.ts
import type { HttpClient, RequestConfig, ResponseData } from '@ldesign/http-core'
import { createHttpClient } from '@ldesign/http-core'
import { useCallback, useEffect, useRef, useState } from 'react'
import { useHttpClient } from './HttpProvider'

export interface UseHttpOptions extends RequestConfig {
  /** 是否立即执行 */
  immediate?: boolean
}

export interface UseHttpReturn<T> {
  /** 响应数据 */
  data: T | null
  /** 加载状态 */
  loading: boolean
  /** 错误信息 */
  error: Error | null
  /** 执行请求 */
  execute: (config?: RequestConfig) => Promise<ResponseData<T>>
  /** 重置状态 */
  reset: () => void
}

/**
 * React HTTP请求 hook
 */
export function useHttp<T = any>(
  url?: string,
  options: UseHttpOptions = {},
): UseHttpReturn<T> {
  // 尝试使用Context中的客户端，否则创建新实例
  const contextClient = useHttpClient()
  const clientRef = useRef<HttpClient>(contextClient || createHttpClient())

  const [data, setData] = useState<T | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<Error | null>(null)

  const { immediate = false, ...requestConfig } = options

  const execute = useCallback(
    async (config?: RequestConfig): Promise<ResponseData<T>> => {
      setLoading(true)
      setError(null)

      try {
        const mergedConfig: RequestConfig = {
          ...requestConfig,
          ...config,
          url: config?.url || url,
        }

        const response = await clientRef.current.request<T>(mergedConfig)
        setData(response.data)
        return response
      }
      catch (err: any) {
        setError(err)
        throw err
      }
      finally {
        setLoading(false)
      }
    },
    [url, requestConfig],
  )

  const reset = useCallback(() => {
    setData(null)
    setLoading(false)
    setError(null)
  }, [])

  // 立即执行
  useEffect(() => {
    if (immediate && url) {
      execute()
    }
  }, [immediate, url, execute])

  return {
    data,
    loading,
    error,
    execute,
    reset,
  }
}

/**
 * GET请求
 */
export function useGet<T = any>(
  url: string,
  options: UseHttpOptions = {},
): UseHttpReturn<T> {
  return useHttp<T>(url, { ...options, method: 'GET' })
}

/**
 * POST请求
 */
export function usePost<T = any>(
  url: string,
  options: UseHttpOptions = {},
): UseHttpReturn<T> {
  return useHttp<T>(url, { ...options, method: 'POST' })
}

/**
 * PUT请求
 */
export function usePut<T = any>(
  url: string,
  options: UseHttpOptions = {},
): UseHttpReturn<T> {
  return useHttp<T>(url, { ...options, method: 'PUT' })
}

/**
 * DELETE请求
 */
export function useDelete<T = any>(
  url: string,
  options: UseHttpOptions = {},
): UseHttpReturn<T> {
  return useHttp<T>(url, { ...options, method: 'DELETE' })
}

/**
 * PATCH请求
 */
export function usePatch<T = any>(
  url: string,
  options: UseHttpOptions = {},
): UseHttpReturn<T> {
  return useHttp<T>(url, { ...options, method: 'PATCH' })
}
